name: ai_photo_scavenger_hunt
description: "A fun photo scavenger hunt game implemented using Flutter and Google AI Dart SDK."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  google_generative_ai: ^0.2.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
