// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSBEE1ii45eZbckU17OfWK5XlODA7PEs',
    appId: '1:49634154974:web:e6cd4d46519646b7cce54f',
    messagingSenderId: '49634154974',
    projectId: 'shapeapp-b3e6c',
    authDomain: 'shapeapp-b3e6c.firebaseapp.com',
    storageBucket: 'shapeapp-b3e6c.firebasestorage.app',
    measurementId: 'G-R7RY1981QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-1PbyQQMlZcHhEJvSsOOWBGz8rp21L0',
    appId: '1:49634154974:android:a0ea13313d374536cce54f',
    messagingSenderId: '49634154974',
    projectId: 'shapeapp-b3e6c',
    storageBucket: 'shapeapp-b3e6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_9Ds7oNTEL5KoaJpnDRVIQImTS4r5RsA',
    appId: '1:49634154974:ios:b492139240bc61b4cce54f',
    messagingSenderId: '49634154974',
    projectId: 'shapeapp-b3e6c',
    storageBucket: 'shapeapp-b3e6c.firebasestorage.app',
    iosBundleId: 'com.example.aiPhotoScavengerHunt',
  );
}
